### ISSUE TITLE
你好，你的项目运行好像缺UserServices这个文件呢

### ISSUE THREAD

**Issue by sunxcode** [xiejiapei-creator/-#1]
No such file or directory
import 'package:jdshop_app/services/UserServices.dart';

**Comment by xiejiapei-creator** [comment]
虽然不知道你是谁，但谢谢提醒，刚才重新上传了文件，应该有你需要的了。但是整个项目太大，只能关键部分，还需要你们配置好环境后才能跑起来。;)



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sunxcode <notifications@github.com&gt;
发送时间: 2020年7月15日 13:49
收件人: xiejiapei-creator/JDShop_Flutter <JDShop_Flutter@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xiejiapei-creator/JDShop_Flutter] 你好，你的项目运行好像缺UserServices这个文件呢 (#1)





 
No such file or directory
 import 'package:jdshop_app/services/UserServices.dart';
